# -*- coding: utf-8 -*-

{
    'name': 'library management search domain',
    'version': '19.0.1.9.0',
    'summary': """Manage Books""",
    'description': """i can perform domain operations.""",
    'category': 'Library management',
    'author': 'Abhay sakariya',
    'company': 'Aktiv software',
    'website': 'https://www.aktivsoftware.com/',
    'depends': ['ak_library_management_orm', 'base_automation'],
    'data': [
        'security/book_reservation_groups.xml',
        'security/book_reservation_rules.xml',
        'security/ir.model.access.csv',
        'data/ir_action_data.xml',
        'data/ir_cron_data.xml',
        'data/mail_template_data.xml',
        'reports/author_report_template.xml',
        'reports/author_reoprt_action.xml',
        'reports/invoice_report.xml',
        'views/active_author_views.xml',
        'views/library_book_views.xml',
        'views/sale_order_views.xml',
        'wizard/add_book_product_views.xml',    
        'views/book_reservation_views.xml',
        'views/res_partner_views.xml',
        'views/book_edition_views.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
